config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :addresses
  resources :customers
  resources :orders
  resources :items

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy

  # Authentication routes
  resources :sessions
  resources :users
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  # Routes for mecidine and procedure costs
  get 'cust_search', to: 'customers#search', as: :cust_search
  get 'item_search', to: 'items#search', as: :item_search

  
  # Set the root url
  root :to => 'home#home'
  
end

app/views/partials/_add_new_object.html.erb
<!-- Add a button for new instances of object -->
  <%= link_to(eval("new_#{model_name}_path"), class: "waves-effect waves-light btn") do %>
    <strong>Add a New <%= model_name.capitalize %></strong>
  <% end %>

app/views/partials/_footer.html.erb
<p class="supertiny">&nbsp;</p>

<div id="footer" class="center-align">
  
  <%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'About Baking Factory', about_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Contact Us', contact_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Privacy Policy', privacy_path %>
  <br />
  <div id="copy">
    Webmaster: <%= mail_to("takhol@andrew.cmu.edu", "Klingon Code Minion", encode: "javascript") %> 
    &nbsp;&nbsp;&copy 2019
  </div>

</div>

app/views/partials/_form_structure.html.erb
<div class="row">
  <div class="col s9">
    <div class="card">    
      <div class="card-content">
        <span class="card-title"><%= type_of_form %></span>
        <%= simple_form_for(object) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%= render partial: "#{fields}", locals: { f: f } %>
          </div>
        </div>
      </div>
    </div>
      <div class="row">
        <div class="form-actions col s9">
          <%= f.button :submit %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= link_to 'Back', :back %>

app/views/partials/_most_items.html.erb
<table class="table table-striped">
<thead>
  <tr>
    <th width="100">Item Name</th>
    <th width="225">Quantity</th>
  </tr>
</thead>
<tbody>
  <% @most_sold.each do |this| %>
    <tr>
      <td><%= this[0].name %></td>
      <td><%= this[1] %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/partials/_nav_guest.html.erb
<nav id="nav">
  <div class="container">
  <ul class="left">
      <li><%= link_to 'Our Catalog', items_path %></li>
    </ul>
    <ul class="right">
      <li><%= link_to 'Login', login_path %></li>
    </ul>
    <ul class="right">
      <li><%= link_to 'Sign Up', new_customer_path %></li>
    </ul>
  </div>
</nav>

app/views/partials/_object_options.html.erb
<% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

<div class="form-actions">
  <% if can? :index, eval(model_name.capitalize) %>
    <%= link_to(eval("#{model_name.pluralize}_path"), class: 'waves-effect waves-light btn') do %>
      &nbsp;Display All <%# model_name.pluralize.capitalize %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>
  
  <% if can? :edit, object %>
    <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'waves-effect waves-light btn') do %>
        &nbsp;<%= "Edit #{opt}" %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>
  
  <% if can?(:destroy, object) && controller.respond_to?(:destroy) %>
    <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'waves-effect waves-light btn btn-alert') do %>
        &nbsp;<%= "Delete #{opt}" %>
    <% end %>
  <% end %>
</div>

app/views/partials/_object_options3.html.erb
<% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

<div class="form-actions">
  <% if can? :index, eval(model_name.capitalize) %>
    <%= link_to(eval("#{model_name.pluralize}_path"), class: 'waves-effect waves-light btn') do %>
      &nbsp;Display All <%# model_name.pluralize.capitalize %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>

</div>

app/views/partials/_order_item_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th width="100">Quantity</th>
      <th width="300">Item</th>
      <th width="100">Unit Price</th>
      <th width="100">Subtotal</th>
      <% if controller.controller_name == 'home' %>
        <th>&nbsp;</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% order_items.each do |oi| %>
      <tr>
        <td align="center"><%= oi.quantity %></td>
        <td><%= link_to oi.item.name, item_path(oi.item) %></td>
        <td align="center"><%= number_to_currency oi.item.price_on_date(date) %></td>
        <td align="right"><%= number_to_currency oi.subtotal(date) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <% if controller.controller_name == 'home' %>
          <td>
            <% if oi.shipped_on.nil? %>
              <%= link_to(image_tag('check_black.gif'), mark_shipped_path(oi.id), method: 'patch') %>
            <% else %>
              <%= link_to(image_tag('check_green.gif'), mark_unshipped_path(oi.id), method: 'patch') %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/partials/_previous_orders.html.erb
<% unless previous_orders.empty? %>
  <div class="panel clearfix">
    <h3>Order History</h3>
    <table>
      <thead>
        <tr>
          <th width="120">Date</th>
          <th width="100">Amount</th>
        </tr>
      </thead>
      <tbody>
      <% previous_orders.each do |order| %>
        <tr>
          <td><%= link_to order.date.strftime('%m/%d/%y'), order_path(order) %></td>
          <td><%= number_to_currency order.grand_total %></td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

app/views/partials/_rev_table.html.erb
<table class="table table-striped">
    <thead>
      <tr>
        <th width="100">Month</th>
        <th width="225">Revenue</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td>January</td>
          <td><%= number_to_currency(@jan_rev) %></td>
        </tr>
        <tr>
          <td>February</td>
          <td><%= number_to_currency(@feb_rev) %></td>
        </tr>
        <tr>
          <td>March</td>
          <td><%= number_to_currency(0) %></td>
        </tr>
        <tr>
          <td>April</td>
          <td><%= number_to_currency(@apr_rev) %></td>
        </tr>
    </tbody>
  </table>

app/views/partials/_structure3.html.erb
<div class="row">
  <div class="col s8">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
  </div>
  <div class="col s4">
    <%= render partial: "#{sidebar}", locals: {previous_orders: previous_orders} unless sidebar.blank? %>
  </div>

  <div class="col s4">
    <%= render partial: "partials/suggestions"%>
  </div>
</div>
<div class="row">
  <%= render :partial => "partials/display_base_errors", locals: {object: object} %>
  <%= render :partial => "partials/object_options", locals: {model_name: model_name, object: object} %>

</div>

app/views/partials/_structure4.html.erb
<div class="row">
  <div class="col s8">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
  </div>
  <div class="col s4">
    <%= render partial: "price_history", locals: {previous_prices: @previous_prices}  unless @previous_prices.empty?%>
  </div>
</div>
<div class="row">
  <%= render :partial => "partials/display_base_errors", locals: {object: object} %>
  <%= render :partial => "partials/object_options", locals: {model_name: model_name, object: object} %>

</div>

app/views/partials/_structure5.html.erb
<div class="row">
  <div class="col s8">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
  </div>
  <div class="col s4">
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>
<div class="row">
  <%= render :partial => "partials/display_base_errors", locals: {object: object} %>
  <%= render :partial => "partials/object_options2", locals: {model_name: model_name, object: object} %>

</div>

app/views/partials/_structure6.html.erb
<div class="row">
  <div class="col s8">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}", locals: {customers: customers} %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
  </div>
  <div class="col s4">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>
<%= render :partial => "partials/object_options3", locals: {model_name: model_name, object: Customer} %>