config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :addresses
  resources :customers
  resources :orders
  resources :items

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy

  # Authentication routes
  resources :sessions
  resources :users
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  # Routes for mecidine and procedure costs
  get 'cust_search', to: 'customers#search', as: :cust_search
  get 'item_search', to: 'items#search', as: :item_search

  
  # Set the root url
  root :to => 'home#home'
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # get modules to help with some functionality
  include AppHelpers::Validations
  include AppHelpers::Deletions
  include AppHelpers::Activeable::InstanceMethods
  extend AppHelpers::Activeable::ClassMethods

  # Relationships
  has_many :orders
  has_many :addresses
  belongs_to :user

  # Allow user to be nested within customer
  accepts_nested_attributes_for :user, reject_if: ->(user) { user[:username].blank? }, allow_destroy: true

  # Scopes
  scope :alphabetical,  -> { order(:last_name).order(:first_name) }
  scope :search, ->(term) { where('first_name LIKE ? OR last_name LIKE ?', "#{term}%", "#{term}%") }


  # Validations
  validates_presence_of :last_name, :first_name
  validates_format_of :phone, with: /\A(\d{10}|\(?\d{3}\)?[-. ]\d{3}[-.]\d{4})\z/, message: "should be 10 digits (area code needed) and delimited with dashes only"
  validates_format_of :email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info))\z/i, message: "is not a valid format"

    # Delegates
  delegate :username, to: :user, allow_nil: true
  
  # Callbacks
  before_save :reformat_phone
  before_update :deactive_user_if_customer_inactive
  before_destroy :cannot_destroy_object

  # Other methods
  def name
    "#{last_name}, #{first_name}"
  end

  def proper_name
    "#{first_name} #{last_name}"
  end

  def billing_address
    self.addresses.active.billing.first
  end

  # Private methods
  private
  def reformat_phone
    self.phone = self.phone.to_s.gsub(/[^0-9]/,"")
  end

  def deactive_user_if_customer_inactive
    if !self.active && !self.user.nil?
      self.user.active = false
      self.user.save
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  include ActionView::Helpers::NumberHelper
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  authorize_resource
  
  def index
    @active_customers = Customer.active.alphabetical.paginate(:page => params[:page]).per_page(10)
    @inactive_customers = Customer.inactive.alphabetical.paginate(:page => params[:page]).per_page(10)
  end

  def show
    @previous_orders = @customer.orders.chronological
    @suggestions = Item.where(category: @customer.orders.first.order_items.first.item.category).first(3)
  end

  def search
    if (params[:query].blank?)
      flash[:error] = "Please Enter a Keyword"
      redirect_to customers_path
    else
      @query = params[:query]
      @customers = Customer.search(@query).alphabetical.paginate(:page => params[:page]).per_page(10)
    end

  end

  def new
    @customer = Customer.new
  end

  def edit
    # reformat phone w/ dashes when displayed for editing (preference; not required)
    @customer.phone = number_to_phone(@customer.phone)
  end

  def create
    @customer = Customer.new(customer_params)
    @user = User.new(user_params)

    unless(current_user.role?(:admin))
      @user.role = "customer"
    end

    if !@user.save
      @customer.valid?
      render action: 'new'
    else
      @customer.user_id = @user.id
      if @customer.save
        if(!current_user.role?(:admin))
          flash[:notice] = "Successfully created #{@customer.proper_name}. Please login with your credentials"
        else
          flash[:notice] = "Successfully created #{@customer.proper_name}."
        end
        
        redirect_to login_path 
      else
        render action: 'new'
      end      
    end
  end
  def update
    respond_to do |format|
      if @customer.update_attributes(customer_params)
        format.html { redirect_to(@customer, :notice => "Successfully updated #{@customer.proper_name}.") }
        format.json { respond_with_bip(@customer) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@customer) }
      end
    end
  end


 
  private
  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :email, :phone, :active)
  end

  def user_params      
    params.require(:customer).permit(:active, :username, :password, :password_confirmation, :role)
  end

end

app/views/customers/_customer_details.html.erb
<div class="card">
  <div class="card-content">
    <h3 id = "bestinplace"><%= best_in_place @customer, :first_name, as: :input %> <%= best_in_place @customer, :last_name, as: :input %></h3><br />

    <b>Phone:&nbsp;&nbsp;</b>
      <div id = "bestinplace"><%= best_in_place @customer, :phone, as: :input %></div><br />
    <b>Email:&nbsp;&nbsp;</b>
      <div id = "bestinplace"><%= best_in_place @customer, :email, as: :input %></div><br />

    <b>Active: &nbsp;&nbsp;</b>
      <%= @customer.active ? "Yes" : "No" %>
      <br><br>

    <p>
      <em>A Baking Factory customer since <%= @customer.created_at.year %>.</em>
    </p>
  </div>
</div>

app/views/customers/_customer_fields.html.erb
<%= f.input :first_name, label_html: { class: 'active' } %>
<%= f.input :last_name, label_html: { class: 'active' } %>
<%= f.input :phone, label_html: { class: 'active' } %>
<%= f.input :email, label_html: { class: 'active' } %>
<%= f.input :active %>

app/views/customers/_customers_list.html.erb
<% if customers.empty? %>
  <p>There are no <%= state.downcase %> customers at this time.</p>
<% else %>

  <table class="striped highlight">
    <thead>
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
        <th class="align_center">Options</th>
    </thead>
    <% for customer in customers %>
      <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">

        <td><%= link_to customer.name, customer_path(customer) %></td>
        <td><%= number_to_phone customer.phone %></td>
        <td><%= mail_to customer.email, customer.email, encode: "javascript"  %></td>


      <td class="align_center">
        <% if can? :edit, customer %>
          <%= link_to edit_customer_path(customer) do %>
                <i class="material-icons">edit</i>
            <% end %>
            &nbsp;&nbsp;&nbsp;&nbsp; 
          <% end %>

      </td>
      </tr>
    <% end %>
  </table>
  <p class="supertiny"></p>
  <br />
  <%= will_paginate customers, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
<% end %>

app/views/customers/_form.html.erb
<%= simple_form_for @customer, html: { class: 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Customer</legend>

    <%= f.input :first_name, input_html: {class: "avg"} %>
    <%= f.input :last_name, input_html: {class: "avg"} %>
    <%= f.input :phone, input_html: {class: "avg"} %>
    <%= f.input :email, input_html: {class: "avg"} %>
    <%= f.input :active %>
    


    <div class="form-actions">
      <%= f.submit nil, :class => 'button radius' %>
      <%= link_to 'Cancel', customers_path, :class => 'button alert radius' %>
    </div>
  </fieldset>
<% end %>

app/views/customers/_search_list.html.erb
  <table class="striped highlight">
    <thead>
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
        <th class="align_center">Options</th>
    </thead>
    <% for customer in customers %>
      <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">

        <td><%= link_to customer.name, customer_path(customer) %></td>
        <td><%= number_to_phone customer.phone %></td>
        <td><%= mail_to customer.email, customer.email, encode: "javascript"  %></td>


      <td class="align_center">
        <% if can? :edit, customer %>
          <%= link_to edit_customer_path(customer) do %>
                <i class="material-icons">edit</i>
            <% end %>
            &nbsp;&nbsp;&nbsp;&nbsp; 
          <% end %>

      </td>
      </tr>
    <% end %>
  </table>
  <p class="supertiny"></p>
  <br />
  <%= will_paginate customers, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>

app/views/customers/_tabbed_index.html.erb
<div id="tabbed">
  <tabs>

    <tab name="Active" v-bind:selected="true">
      <%= render :partial => "customers_list", locals: {customers: @active_customers, state: 'active'} %>
    </tab>

    <tab name="Inactive">
      <%= render :partial => "customers_list", locals: {customers: @inactive_customers, state: 'inactive'} %>
    </tab>

  </tabs>
</div>

<p>&nbsp;</p>
<%= render :partial => "partials/add_new_object", locals: {model_name: 'customer'} %>

app/views/customers/_user_fields.html.erb
<%= f.input :username, label_html: { class: 'active' } %>
<%= f.input :password, label_html: { class: 'active' } %>
<%= f.input :password_confirmation, label_html: { class: 'active' } %>

app/views/customers/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @customer, 
                                                        type_of_form: "New Customer",
                                                        fields: "customer_fields"} %>

app/views/customers/index.html.erb
<% if logged_in? && current_user.role = 'admin' %>
<%= render partial: "partials/structure1", locals: {model_name: "customer", 
                                                         primary: "tabbed_index", 
                                                         secondary: nil,
                                                         sidebar: "partials/title_with_search"} %>
<% else %>
<%= render partial: "partials/structure1", locals: {model_name: "customer", 
                                                         primary: "tabbed_index", 
                                                         secondary: nil,
                                                         sidebar: nil} %>
<% end %>

app/views/customers/new.html.erb
<%= render partial: "partials/form2_structure", locals: {object: @customer, 
                                                        type_of_form: "New Customer",
                                                        fields1: "customer_fields",
                                                        section_2: "User Account",
                                                        fields2: "user_fields"} %>

app/views/customers/search.html.erb
<% if logged_in? && current_user.role = 'admin' %>
<%= render partial: "partials/structure6", locals: {model_name: "customer",
                                                        customers: @customers,
                                                         primary: "search_list", 
                                                         secondary: nil,
                                                         sidebar: "partials/title_with_search"} %>
<% else %>
<%= render partial: "partials/structure1", locals: {model_name: "customer", 
                                                         primary: "tabbed_index", 
                                                         secondary: nil,
                                                         sidebar: nil} %>
<% end %>

app/views/customers/show.html.erb
<%= render partial: "partials/structure3", locals: {model_name: "customer", 
                                                         object: @customer,
                                                         primary: "customer_details",
                                                         previous_orders: @previous_orders,
                                                         secondary: nil,
                                                         sidebar: "partials/previous_orders"} %>

                                                         