config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :addresses
  resources :customers
  resources :orders
  resources :items

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy

  # Authentication routes
  resources :sessions
  resources :users
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  # Routes for mecidine and procedure costs
  get 'cust_search', to: 'customers#search', as: :cust_search
  get 'item_search', to: 'items#search', as: :item_search

  
  # Set the root url
  root :to => 'home#home'
  
end

app/models/order.rb
class Order < ApplicationRecord
  # get module to help with some functionality
  include AppHelpers::Validations
  include AppHelpers::Deletions
  include AppHelpers::Shipping
  require 'base64'

  # Relationships
  belongs_to :customer
  belongs_to :address
  has_many :order_items
  has_many :items, through: :order_items

  # Virtual attributes (non-saved)
  attr_accessor :credit_card_number
  attr_accessor :expiration_year
  attr_accessor :expiration_month

  # Scopes
  scope :chronological, -> { order(date: :desc) }
  scope :paid,          -> { where.not(payment_receipt: nil) }
  scope :for_customer,  ->(customer_id) { where(customer_id: customer_id) }

  # Class methods
  def self.not_shipped
    # joins(:order_items).where("order_items.shipped_on IS NULL").to_a.uniq
    joins(:order_items).where("order_items.shipped_on IS NULL").distinct

  end

  def self.rev_for_month(month)

    sum = 0

    orders = []

    Order.paid.each do |order|
      if order.date.year == 2019
        orders.push(order)
      end
    end


    orders.each do |order|
      if order.date.month == month
        sum += order.grand_total
      end
    end

    sum
  end

  # Other methods
  def unshipped_items
    self.order_items.unshipped
  end



  # Validations
  #validates_date :date
  #validates_numericality_of :grand_total, greater_than_or_equal_to: 0, allow_blank: true
  validates_presence_of :customer_id, :address_id
  validate :customer_is_active_in_system
  validate :address_is_active_in_system
  validate :credit_card_number_is_valid
  validate :expiration_date_is_valid

  # Other methods
  def is_editable?
    !self.order_items.unshipped.empty?
  end

  def pay
    return false unless self.payment_receipt.nil?
    generate_payment_receipt
    self.save!
    self.payment_receipt
  end

  def total_weight
    weight = self.order_items.inject(0){|sum, oi| sum += oi.item.weight * oi.quantity}
  end

  def shipping_costs
    calculate_shipping_costs(self.total_weight, base=2.00)
  end

  def credit_card_type
    credit_card.type.nil? ? "N/A" : credit_card.type.name
  end

  # Callbacks
  before_destroy do
    check_if_any_order_items_shipped
    if errors.present?
      @destroyable = false
      throw(:abort)
    end
    remove_order_items
  end

  private
  def customer_is_active_in_system
    is_active_in_system(:customer)
  end

  def address_is_active_in_system
    is_active_in_system(:address)
  end

  def generate_payment_receipt
    self.payment_receipt = Base64.encode64("order: #{self.id}; amount_paid: #{self.grand_total}; received: #{self.date}; card: #{self.credit_card_type} ****#{self.credit_card_number[-4..-1]}; billing zip: #{self.customer.billing_address.zip}")
  end

  def credit_card
    CreditCard.new(self.credit_card_number, self.expiration_year, self.expiration_month)
  end

  def credit_card_number_is_valid
    return false if self.expiration_year.nil? || self.expiration_month.nil?
    if self.credit_card_number.nil? || credit_card.type.nil?
      errors.add(:credit_card_number, "is not valid")
      return false
    end
    true
  end

  def expiration_date_is_valid
    return false if self.credit_card_number.nil? 
    if self.expiration_year.nil? || self.expiration_month.nil? || credit_card.expired?
      errors.add(:expiration_year, "is expired")
      return false
    end
    true
  end

  def check_if_any_order_items_shipped
    unless self.order_items.shipped.empty?
      errors.add(:base, "This order has already been partially shipped and therefore cannot be deleted.")
    end
  end

  def remove_order_items
    self.order_items.each{ |oi| oi.destroy }
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include AppHelpers::Cart
  before_action :set_order, only: [:show, :destroy]
  before_action :check_login
  authorize_resource

  def index
    if current_user.role?(:customer)
      @all_orders = current_user.customer.orders.chronological.paginate(page: params[:page]).per_page(10)
    else
      @all_orders = Order.chronological.paginate(:page => params[:page]).per_page(10)
    end
    
  end

  def show
    @orderitems = @order.order_items
    get_related_data()
  end

  def new
    @cart = create_cart
  end

  def create
    @order = Order.new(order_params)
    @order.date = Date.current
    if @order.save
      @order.pay
      redirect_to @order, notice: "Thank you for ordering from the Baking Factory."
    else
      render action: 'new'
    end
  end

  # def update
  #   if @visit.update_attributes(visit_params)
  #     flash[:notice] = "Successfully updated visit by #{@visit.pet.name}."
  #     redirect_to @visit
  #   else
  #     render action: 'edit'
  #   end
  # end


  private
  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:address_id, :customer_id, :grand_total)
  end
  def get_related_data
    @customer = @order.customer
    @orderitems = @order.order_items.to_a.sort_by{|i| i.item.name}
    @total = @order.grand_total
  end

end

app/views/orders/_all_orders.html.erb
<% if @all_orders.empty? %>
  <p><em>There are no orders at this time.</em></p>
<% else %>
  <%= render :partial => "order_list", locals: {status: 'All', orders: @all_orders} %>  
<% end %>
<br />

app/views/orders/_fields.html.erb
    <%= f.input :customer_id, collection: Customer.active.alphabetical, include_blank: true, input_html: {class: "avg"} %>
    <%= f.input :address_id, collection: get_address_options, include_blank: true, input_html: {class: "avg"} %>
    <%= f.input :grand_total, as: :string, input_html: {class: "avg"} %>

app/views/orders/_form.html.erb
<%= simple_form_for @order, html: { class: 'form-horizontal' } do |f| %>
  <fieldset>
    <legend>Place an Order with the Baking Factory</legend>

    <%= f.input :customer_id, collection: Customer.active.alphabetical, include_blank: true, input_html: {class: "avg"} %>
    <%= f.input :address_id, collection: get_address_options, include_blank: true, input_html: {class: "avg"} %>
    <%= f.input :grand_total, as: :string, input_html: {class: "avg"} %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'button radius' %>
      <%= link_to 'Cancel', orders_path, :class => 'button alert radius' %>
    </div>
  </fieldset>
<% end %>

app/views/orders/_order_details.html.erb
<h3>Order Details</h3>

<p>
  <b>Date</b>: <%= @order.date.strftime('%B %e, %Y') %>
</p>

<p>
  <b>Customer</b>: <%= link_to @order.customer.name, customer_path(@order.customer) %>
</p>

<p>
  <b>Recipient</b>: <%= link_to @order.address.recipient, address_path(@order.address) %>
</p>

<p>
  <b>Total Cost</b>: <%= number_to_currency @order.grand_total %>
</p>


<p>
  <em>Thanks for being a Baking Factory customer since <%= @order.customer.created_at.year %>.</em>
</p>

app/views/orders/_order_items.html.erb
  <h4>Orders Items</h4>
  <table class="table table-striped">
    <thead>
      <tr>
        <th width="100">Name</th>
        <th width="225">Quantity</th>
      </tr>
    </thead>
    <tbody>
      <% @orderitems.each do |item| %>
        <tr>
          <td><%= link_to item.item.name, item_path(item.item) %></td>
          <td><%= item.quantity %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/orders/_order_list.html.erb
  <h4><%= status %> Orders</h4>
  <table class="table table-striped">
    <thead>
      <tr>
        <th width="100">Date</th>
        <th width="225">Customer</th>
        <th width="225">Recipient</th>
        <th width="100">Cost</th>
      </tr>
    </thead>
    <tbody>
      <% orders.each do |order| %>
        <tr>
          <td><%= link_to order.date.strftime('%m/%d/%y'), order_path(order) %></td>
          <td><%= link_to order.customer.name, customer_path(order.customer) %></td>
          <td><%= link_to order.address.recipient, address_path(order.address) %></td>
          <td><%= number_to_currency order.grand_total %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%= will_paginate orders, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>  

app/views/orders/_tabbed_index.html.erb
<div id="tabbed">
  <tabs>

    <tab name="breads" v-bind:selected="true">
      <%= render :partial => "items_list", locals: {items: @breads, item_type: 'breads'} %>
    </tab>

    <tab name="muffins">
      <%= render :partial => "items_list", locals: {items: @muffins, item_type: 'muffins'} %>
    </tab>

    <tab name="pastries">
      <%= render :partial => "items_list", locals: {items: @pastries, item_type: 'pastries'} %>
    </tab>

  </tabs>
</div>

<p>&nbsp;</p>
<% if logged_in? && current_user.role == 'admin' %>
  <%= render :partial => "partials/add_new_object", locals: {model_name: 'item'} %>
<% end %>

app/views/orders/index.html.erb
<%= render partial: "partials/index_structure", locals: {model_name: "order", 
                                                         primary: "all_orders", 
                                                         secondary: nil,
                                                         sidebar: nil} %>

app/views/orders/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @order, 
                                                        type_of_form: "Place an Order with the Baking Factory",
                                                        fields: "fields"} %>

app/views/orders/show.html.erb
<%= render partial: "partials/structure5", locals: {model_name: "order", 
                                                         object: @order,
                                                         primary: "order_details", 
                                                         secondary: nil,
                                                         sidebar: 'order_items'} %>