config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :addresses
  resources :customers
  resources :orders
  resources :items

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy

  # Authentication routes
  resources :sessions
  resources :users
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  # Routes for mecidine and procedure costs
  get 'cust_search', to: 'customers#search', as: :cust_search
  get 'item_search', to: 'items#search', as: :item_search

  
  # Set the root url
  root :to => 'home#home'
  
end

app/models/item.rb
class Item < ApplicationRecord
  # get modules to help with some functionality
  include AppHelpers::Validations
  include AppHelpers::Deletions
  include AppHelpers::Activeable::InstanceMethods
  extend AppHelpers::Activeable::ClassMethods

  # List of allowable categories
  CATEGORIES = [['Bread','bread'],['Muffins','muffins'],['Pastries','pastries']]

  # Relationships
  has_many :order_items
  has_many :item_prices
  has_many :orders, through: :order_items

  # Scopes
  scope :alphabetical, -> { order(:name) }
  scope :active,       -> { where(active: true) }
  scope :inactive,     -> { where(active: false) }
  scope :for_category, ->(category) { where(category: category) }
  scope :random_items, -> { order(Item.all.to_a.shuffle) }
  scope :search, ->(term) { where('name LIKE ? OR category LIKE ?', "#{term}%","#{term}%") }
  
  # Validations
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates_numericality_of :units_per_item, only_integer: true, greater_than: 0
  validates_numericality_of :weight, greater_than: 0
  validates_inclusion_of :category, in: CATEGORIES.map{|key, value| value}, message: "is not an option"
  # validates_inclusion_of :category, in: CATEGORIES.to_h.values, message: "is not an option"

  def self.most_sold
    result = Hash.new

    Item.active.each do |item|
      result[item] = 0
    end

    OrderItem.all.each do |oi|
      result[oi.item] += oi.quantity
    end

    result.sort_by { |name, num| num }.reverse.first(5)

  end

  # Other methods
  def current_price
    curr = self.item_prices.current.first
    if curr.nil?
      return nil
    else
      return curr.price
    end
  end

  def to_bake
    res = 0

    stuff = OrderItem.unshipped
    newstuff = stuff.where(item_id: self.id)
    newstuff.each do |oi|
      res += oi.quantity
    end

    res
  end

  def self.to_ship(category)
    res = []

    this = Item.for_category(category)

    this.each do |item|
      item.order_items.unshipped.each do |oi|
        res.push(oi)
      end
    end

    res


  end

  def price_on_date(date)
    data = self.item_prices.for_date(date).first
    if data.nil?
      return nil
    else
      return data.price
    end
  end

  # Callbacks
  before_destroy do 
    check_if_ever_associated_with_an_order
    if errors.present?
      @destroyable = false
      throw(:abort)
    else
      remove_unshipped_and_unpaid_order_items
    end
  end
  after_destroy :remove_unshipped_and_unpaid_order_items
  after_rollback :convert_to_inactive


  private
  def check_if_ever_associated_with_an_order
    unless self.order_items.shipped.empty?
      errors.add(:base, "This item cannot be deleted because it has been part of a shipped order, but its status has been set to inactive.")
    end
  end

  def convert_to_inactive
    if !@destroyable.nil? && @destroyable == false
      remove_unshipped_and_unpaid_order_items
      make_inactive
    end
    @destroyable = nil
  end

  def remove_unshipped_and_unpaid_order_items
    self.order_items.unshipped.each{|oi| oi.destroy if oi.order.payment_receipt.nil?}
  end


end

app/controllers/items_controller.rb
  class ItemsController < ApplicationController
  before_action :check_login, except: [:index, :show]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  authorize_resource
  
  def index
    # get info on active items for the big three...
    @breads = Item.active.for_category('bread').alphabetical.paginate(:page => params[:page]).per_page(10)
    @muffins = Item.active.for_category('muffins').alphabetical.paginate(:page => params[:page]).per_page(10)
    @pastries = Item.active.for_category('pastries').alphabetical.paginate(:page => params[:page]).per_page(10)

    @breads_todo = Item.active.for_category('bread').alphabetical.paginate(:page => params[:page]).per_page(10)
    @muffins_todo = Item.active.for_category('muffins').alphabetical.paginate(:page => params[:page]).per_page(10)
    @pastries_todo = Item.active.for_category('pastries').alphabetical.paginate(:page => params[:page]).per_page(10)

    @breads_toship = Item.to_ship('bread')
    @muffins_toship = Item.to_ship('muffins')
    @pastries_toship= Item.to_ship('pastries')
    
    # get a list of any inactive items for sidebar
    @inactive_items = Item.inactive.alphabetical.paginate(:page => params[:page]).per_page(10)
  end

  def show
    @previous_prices = @item.item_prices.chronological.to_a
    # everyone sees similar items in the sidebar
    @similar_items = Item.for_category(@item.category).alphabetical.to_a
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def search
    if (params[:query].blank?)
      flash[:error] = "Please Enter a Keyword"
      redirect_to items_path
    else
      @query = params[:query]
      @items = Item.search(@query).alphabetical.paginate(:page => params[:page]).per_page(10)
    end

  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to @item, notice: "#{@item.name} was added to the system."
    else
      render action: 'new'
    end
  end

  def update
    if @item.update(item_params)
      redirect_to @item, notice: "#{@item.name} was revised in the system."
    else
      render action: 'edit'
    end
  end

  def destroy
    @item.destroy
    redirect_to items_url, notice: "#{@item.name} was removed from the system."
  end

  private
  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :description, :picture, :category, :units_per_item, :weight, :active)
  end

end

app/views/items/_fields.html.erb
<%= f.input :name, label_html: { class: 'active' } %>
<%= f.input :description, label_html: { class: 'active' } %>
<%= f.input :category, label_html: { class: 'active' } %>
<%= f.input :picture, as: :file, label_html: { class: 'active' } %>
<%= f.input :units_per_item, label_html: { class: 'active' } %>
<%= f.input :weight, label_html: { class: 'active' } %>
<%= f.input :active %>

app/views/items/_item_data.html.erb
<div class="card">
  <div class="card-content">
    <h4><%= @item.name %></h4><br />

    <% unless @item.picture.blank? %>
        <%= image_tag(@item.picture)%><br /><br />
    <% end %>
        <b>Description:&nbsp;&nbsp;</b>
        <%= @item.description%><br /><br />

        <b>Weight (lbs):&nbsp;&nbsp;</b>
        <%= @item.weight%><br /><br />

        <b>Price:&nbsp;&nbsp;</b>
        <%= number_to_currency(@item.current_price) %><br />
  </div>
</div>

app/views/items/_items_list.html.erb
<h4><%= item_type.capitalize %></h4>

<% if items.empty? %>
  <p><em>There are no items of this category at this time.</em></p>
<% else %>


  <table class="table table-striped">
    <thead>
        <th>Name</th>
        <th>Price</th>
        <th>Units</th>
        <% if can? :edit, Item %>
          <th class="align_center">Options</th>
        <% end %>

    </thead>
    <% for item in items %>
      <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
        <td><%= link_to item.name, item_path(item) %></td>
        <td><%= number_to_currency item.current_price %></td>
        <td><%= item.units_per_item %> <%= item_type == 'breads' ? 'loaf' : item_type %></td>

        <td class="align_center">
          <% if can? :edit, item %>
            <%= link_to edit_item_path(item) do %>
                  <i class="material-icons">edit</i>
              <% end %>
              &nbsp;&nbsp;&nbsp;&nbsp; 
            <% end %>
            <% if can? :destroy, item %>
              <%= link_to(item_path(item), method: :delete, data: { confirm: 'Are you sure you wish to delete this information?' }) do %>
                  <i class="material-icons">delete</i>
              <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <p class="supertiny"></p>
  <br />
  <%= will_paginate items, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
<% end %>

app/views/items/_price_history.html.erb
<% unless @previous_prices.empty? %>
  <div class="card">
    <div class="card-content">
      <span class="card-title">Price History</span>
      <table class="striped highlight">
      <thead>
        <th>Date</th>
        <th class="align_right">Price</th>
      </thead>
        <% for price in @previous_prices %>
          <tr>
            <td><%= price.start_date.strftime("%b %d, %Y") %></td>
          <td class="align_right"><%= number_to_currency(price.price) %></td>
          </tr>
        <% end %>
    </table>
    </div>
    <% if can? :new, ItemPrice %>
      <div class="card-action">
        <%= link_to "Add a new price", new_item_price_path(item_id: @item.id) %>
      </div>
    <% end %>
  </div>
<% else %>
  <% if can? :new, ItemPrice %>
    <div class="card grey lighten-3">
      <div class="card-action">
        <%= link_to "Add a new price", new_item_price_path(item_id: @item.id) %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/items/_search_list.html.erb
<table class="table table-striped">
    <thead>
        <th>Name</th>
        <th>Price</th>
        <% if can? :edit, Item %>
          <th class="align_center">Options</th>
        <% end %>

    </thead>
    <% for item in items %>
      <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
        <td><%= link_to item.name, item_path(item) %></td>
        <td><%= number_to_currency item.current_price %></td>

        <td class="align_center">
          <% if can? :edit, item %>
            <%= link_to edit_item_path(item) do %>
                  <i class="material-icons">edit</i>
              <% end %>
              &nbsp;&nbsp;&nbsp;&nbsp; 
            <% end %>
            <% if can? :destroy, item %>
              <%= link_to(item_path(item), method: :delete, data: { confirm: 'Are you sure you wish to delete this information?' }) do %>
                  <i class="material-icons">delete</i>
              <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <p class="supertiny"></p>
  <br />
  <%= will_paginate items, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>

app/views/items/_similar_items.html.erb
  <div class="panel clearfix">
  <h3>Similar Items</h3>
  <table>
    <thead>
      <tr>
        <th width="120">Name</th>
        <th width="100">Price</th>
      </tr>
    </thead>
    <tbody>
    <% @similar_items.each do |item| %>
      <tr>
        <td><%= link_to item.name, item_path(item) %></td>
        <td><%= number_to_currency item.current_price %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/items/_tabbed_index.html.erb
<div id="tabbed">
  <tabs>

  
    <tab name="breads" v-bind:selected="true">
      <%= render :partial => "items_list", locals: {items: @breads, item_type: 'breads'} %>
    </tab>

    <tab name="muffins">
      <%= render :partial => "items_list", locals: {items: @muffins, item_type: 'muffins'} %>
    </tab>

    <tab name="pastries">
      <%= render :partial => "items_list", locals: {items: @pastries, item_type: 'pastries'} %>
    </tab>

  </tabs>
</div>

<p>&nbsp;</p>
<% if logged_in? && current_user.role == 'admin' %>
  <%= render :partial => "partials/add_new_object", locals: {model_name: 'item'} %>
<% end %>

app/views/items/_todo_list.html.erb
<h4><%= item_type.capitalize %></h4>

<% if items.empty? %>
  <% if logged_in? && current_user.role == 'baker'%>
          <p>No items of this category to bake</p>
        <% end %>
        <% if logged_in? && current_user.role == 'shipper'%>
        <p>No items of this category to ship</p>
        <% end %>
<% else %>


  <table class="table table-striped">
    <thead>
        <% if logged_in? && current_user.role == 'baker'%>
          <th>Name</th>
          <th>Quantity to Bake</th>
        <% end %>
        <% if logged_in? && current_user.role == 'shipper'%>
          <th>Order Items to Ship</th>
          <th>Address</th>
          <th class="align_center">Options</th>
        <% end %>
    </thead>
    <% for item in items %>
      <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
        <% if logged_in? && current_user.role == 'baker'%>
          <td><%= link_to item.name, item_path(item) %></td>
          <td><%= item.to_bake %> <%= item_type == 'breads' ? 'loaf' : item_type %></td>
        <% end %>
        <% if logged_in? && current_user.role == 'shipper' && item.shipped_on.blank?%>
          <th><%= link_to item.item.name, item_path(item.item) %></th>
          <th><%= link_to item.order.address.formatted, address_path(item.order.address) %></th>
          <%= link_to(order_item_path(item), method: :edit) do %>
            <i class="material-icons">check</i>
        <% end %>
        <% end %>

      </tr>
    <% end %>
  </table>
  <p class="supertiny"></p>
  <br />
  <%= will_paginate items, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
<% end %>

app/views/items/_todo_tabbed.html.erb
<div id="tabbed">
  <tabs>

    <% if logged_in? && current_user.role == 'baker'%>
    <tab name="breads" v-bind:selected="true">
        <%= render :partial => "todo_list", locals: {items: @breads_todo, item_type: 'breads'} %>
    </tab>

    <tab name="muffins">
        <%= render :partial => "todo_list", locals: {items: @muffins_todo, item_type: 'muffins'} %>
    </tab>

    <tab name="pastries">
        <%= render :partial => "todo_list", locals: {items: @pastries_todo, item_type: 'pastries'} %>
    </tab>
    <% end %>
    
    <% if logged_in? && current_user.role == 'shipper'%>
        <tab name="breads" v-bind:selected="true">
        <%= render :partial => "todo_list", locals: {items: @breads_toship, item_type: 'breads'} %>
        </tab>

        <tab name="muffins">
        <%= render :partial => "todo_list", locals: {items: @muffins_toship, item_type: 'muffins'} %>
        </tab>

        <tab name="pastries">
        <%= render :partial => "todo_list", locals: {items: @pastries_toship, item_type: 'pastries'} %>
        </tab>
    <% end %>
   

  </tabs>
</div>

<p>&nbsp;</p>
<% if logged_in? && current_user.role == 'admin' %>
  <%= render :partial => "partials/add_new_object", locals: {model_name: 'item'} %>
<% end %>

app/views/items/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @item, 
                                                        type_of_form: "Edit Item",
                                                        fields: "fields"} %>

app/views/items/index.html.erb
<% if logged_in? && (current_user.role == 'baker' ||current_user.role == 'shipper') %>
<%= render partial: "partials/structure5", locals: {model_name: "item",
                                                        object: @item,
                                                         primary: "todo_tabbed", 
                                                         secondary: nil,
                                                         sidebar: nil} %>

<% else %>
<%= render partial: "partials/structure1", locals: {model_name: "item", 
                                                         primary: "tabbed_index", 
                                                         secondary: nil,
                                                         sidebar: "partials/item_search_bar"} %>
<% end %>

app/views/items/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @item, 
                                                        type_of_form: "New Item",
                                                        fields: "fields"} %>

app/views/items/search.html.erb
<%= render partial: "partials/structure7", locals: {model_name: "item",
                                                        items: @items,
                                                         primary: "search_list", 
                                                         secondary: nil,
                                                         sidebar: "partials/item_search_bar"} %>

app/views/items/show.html.erb
<% if logged_in? && current_user.role == 'admin' %>
    <%= render partial: "partials/structure4", locals: {model_name: "item", 
                                                            object: @item,
                                                            primary: "item_data", 
                                                            secondary: nil,
                                                            sidebar: nil} %>

<% else %>
    <%= render partial: "partials/structure2", locals: {model_name: "item", 
                                                            object: @item,
                                                            primary: "item_data", 
                                                            secondary: nil,
                                                            sidebar: "similar_items"} %>

<% end %>